//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstComp.DBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_list
    {
        public int ID { get; set; }
        public string Адрес_объекта { get; set; }
        public string Дата_сдачи { get; set; }
        public string Номер_клиента { get; set; }
        public string ФИО_клиента { get; set; }
    }
}
