//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConstComp.DBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Providers
    {
        public int ID { get; set; }
        public string Поставщик { get; set; }
        public string Адрес { get; set; }
        public string Телефон { get; set; }
    }
}
